name: windows1251
version: 2.0.0
description: Cyrillic windows-1251 (cp1251) encoding implementation for Dart.
repository: https://github.com/ykmnkmi/windows1251.dart
topics: [cyrrylic, windows-1251, cp1251, encode, decode]
funding: [https://www.buymeacoffee.com/ykmnkmi]

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
