name: windows1251
description: Cyrillic Windows-1251 / cp-1251 encoding for Dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
